name: The Only Tip. The Only Edge.
url: "http://blog.kazuya.co/"
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
paginate: 5
paginate_path: "/page:num"
archive: []
highlighter: rouge
plugins:
  - jekyll-paginate